import type { Metadata } from "next";
import { Geist, Fraunces, Figtree } from "next/font/google";
import "./globals.css";
import { cn } from "~/lib/utils";
import { TooltipProvider } from "~/components/ui/tooltip";
import { Toaster } from "~/components/ui/toast";
import { PageTransitionLoader } from "~/components/general/page-transition-loader";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Fraunces({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        figtree.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <TooltipProvider>
          {children}
          <PageTransitionLoader />
        </TooltipProvider>
        <Toaster />
      </body>
    </html>
  );
}